# Generated by Django 6.0.2 on 2026-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_address_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Posted', 'Posted'), ('Unposted', 'Unposted')], default='Posted', max_length=20)),
                ('assigned_employees', models.ManyToManyField(blank=True, to='employees.employee')),
            ],
        ),
    ]
