# Generated by Django 6.0.3 on 2026-05-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('scheduling', '0002_scheduleevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('Schedule Change', 'Schedule Change'), ('Overtime', 'Overtime')], max_length=100)),
                ('overtime_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='scheduling.scheduleevent')),
            ],
        ),
    ]
