# Generated by Django 6.0.2 on 2026-05-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computations', '0001_initial'),
        ('runPayroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='runPayroll.payrollrun'),
        ),
    ]
